export * from './getNature'
export * from './getPokemon'
export * from './getAbility'
export * from './getEggGroup'
export * from './getAllPokemon'
export * from './getItem'
export * from './getSpecie'
export * from './getLocations'